import '../../theme/globals.css'
import type { Metadata } from 'next'
import { SomeChildrenInterface } from '@/utils/types/layout.type'
import { SessionProvider } from '@/providers/sessionProvider'
import { LoadingProvider } from '@/providers/loadingProvider/loadingProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: SomeChildrenInterface) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`antialiased`}>
        {/* Aqui vai ter o header global para a landing pagee client  */}
        <SessionProvider>
          <LoadingProvider>{children}</LoadingProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
