import '../../theme/globals.css';
import type { Metadata } from 'next';
import { SomeChildrenInterface } from '@/utils/types/generics/layout.type';
import { SessionProvider } from '@/providers/sessionProvider';
import { LoadingProvider } from '@/providers/loadingProvider/loadingProvider';
import { Toaster } from 'react-hot-toast';
import { Provider } from '@/components/ui/provider';
import { CartProvider } from '@/providers/cartContext/cartProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: SomeChildrenInterface) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`antialiased`}>
        <SessionProvider>
          <LoadingProvider>
            <CartProvider>
              <Provider>{children}</Provider>
            </CartProvider>
          </LoadingProvider>
        </SessionProvider>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
