name: FrontEnd CI

on:
  push:
    branches:
      - main
      - develop
      - 'feat/*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: checar o código do repositório
        uses: actions/checkout@v3

      - name: Using node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Run install build and tests
        run: |
          npm ci
          npm run lint
          npm run build
